accounts/urls.py
from django.urls import path


# accounts views
from accounts.views import SignupView
from accounts.views import UserLogout
from accounts.views import UserLoginView

app_name = 'accounts'


urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', UserLogout.as_view(), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.views import serve
from django.conf import settings


# Apps Urls
from accounts import urls as accounts_urls
from authority import urls as authority_urls
from customer import urls as customer_urls
from home import urls as home_urls
from payment import urls as payment_urls
from report import urls as report_urls
from shipping import urls as shipping_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(accounts_urls)),
    path('', include(authority_urls)),
    path('', include(customer_urls)),
    path('', include(home_urls)),
    path('', include(payment_urls)),
    path('', include(report_urls)),
    path('', include(shipping_urls)),

]

# for serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, view=serve)

home/urls.py
from django.urls import path

# Views
from home.views import home_main
from home.views import customer_message

app_name = 'home'

urlpatterns = [

    path('', home_main.IndexView.as_view(),name="index"),
    path('home/', home_main.IndexView.as_view(),name="home"),
    path('contact/', home_main.ContactView.as_view(),name="contact"),
    
]

urlpatterns += [
    path('customer-message/', customer_message.CustomerMessageView.as_view(), name='customer_message'),
]

home/models.py
from django.db import models

# Create your models here.
class CustomerMessage(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    message = models.TextField()
    send_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return str(f"{self.name}'s message")

home/forms.py
from django import forms

# models
from home.models import CustomerMessage


class CustomerMessageForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Enter Your Name'})
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'placeholder': 'Enter Your Email'})
    )
    message = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Write your message here'})
    )

    class Meta:
        model = CustomerMessage
        fields = ('name','email','message')

home/views/customer_message.py
from django.http import JsonResponse
# Generic Classes
from django.views.generic import CreateView

# models 
from home.models import CustomerMessage

# forms
from home.forms import CustomerMessageForm

class CustomerMessageView(CreateView):
    model = CustomerMessage
    form_class = CustomerMessageForm
    http_method_names = ['get', 'post']

    def form_valid(self, form):

        if form.is_valid():
            form.save()
            data={
                'ok':'ok'
            }
            return JsonResponse({'message': 'success', 'data': {'error_message': 'There was a problem processing your request.'}})
        else:
            return JsonResponse({'message': 'error', 'data': form.errors})

home/templates/home_base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="eng">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> {% block title %}{% endblock title %} </title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href=" {% static 'assets/css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" type="text/css">

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>

     <!-- jaquery cdn link -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="header__top__left">
                            <ul>
                                <li><i class="fa fa-envelope"></i>sasomona8@gmail.com</li>
                                {% comment %} <li>Free Shipping for all Order of $99</li> {% endcomment %}
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="header__top__right">
                            <div class="header__top__right__social">
                                <a href="https://www.facebook.com/somona.akter.16144" target="_blank"><i class="fa fa-facebook"></i></a>
                                <a href="https://www.facebook.com/somona.akter.16144"><i class="fa fa-twitter"></i></a>
                                <a href="https://www.facebook.com/somona.akter.16144"><i class="fa fa-linkedin"></i></a>
                                <a href="https://www.facebook.com/somona.akter.16144"><i class="fa fa-pinterest-p"></i></a>
                            </div>
                            <div class="header__top__right__auth">
                                {% if user.is_authenticated %}
                                    <a href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa fa-user"></i>Profile</a>
                                {% else %}
                                    <a href="{% url 'accounts:login' %}"><i class="fa fa-user"></i> Login</a>
                                    
                                {% endif %}
                                    <ul class="dropdown-menu">
                                      <li><a class="dropdown-item" href="#">Customer Arena</a></li>
                                      <li><a class="dropdown-item" href="#">Manage Profile</a></li>
                                      <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
                                    </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="header__logo">
                        <a href="{% url 'home:index' %}">
                            <h3 class="text-success fw-bold"><i class="fa-solid fa-burger text-primary me-2"></i>SIZZ<span class="text-primary">LING</span></h3>
                        </a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <nav class="header__menu">
                        <ul>
                            <li class="active"><a href="{% url 'home:index' %}">Home</a></li>
                            <li><a href="./shop-grid.html">Shop</a></li>
                            <li><a href="#">Pages</a>
                                <ul class="header__menu__dropdown">
                                    <li><a href="./shop-details.html">Shop Details</a></li>
                                    <li><a href="./shoping-cart.html">Shoping Cart</a></li>
                                    <li><a href="./checkout.html">Check Out</a></li>
                                    <li><a href="./blog-details.html">Blog Details</a></li>
                                </ul>
                            </li>
                            <li><a href="./blog.html">Blog</a></li>
                            <li><a href="{% url 'home:contact' %}">Contact</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3">
                    <div class="header__cart">
                        <ul>
                            <li><a href="#"><i class="fa fa-heart"></i> <span>1</span></a></li>
                            <li><a href="#"><i class="fa fa-shopping-bag"></i> <span>3</span></a></li>
                        </ul>
                        <div class="header__cart__price">item: <span>$150.00</span></div>
                    </div>
                </div>
            </div>
            <div class="humberger__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>
    <!-- Header Section End -->

    <!-- Hero Section Begin -->
    <section class="hero hero-normal">
        <div class="container">
            <div class="row">
                {% comment %} <div class="col-lg-3">
                    <div class="hero__categories">
                        <div class="hero__categories__all">
                            <i class="fa fa-bars"></i>
                            <span>All departments</span>
                        </div>
                        <ul>
                            <li><a href="#">Fresh Meat</a></li>
                            <li><a href="#">Vegetables</a></li>
                            <li><a href="#">Fruit & Nut Gifts</a></li>
                            <li><a href="#">Fresh Berries</a></li>
                            <li><a href="#">Ocean Foods</a></li>
                            <li><a href="#">Butter & Eggs</a></li>
                            <li><a href="#">Fastfood</a></li>
                            <li><a href="#">Fresh Onion</a></li>
                            <li><a href="#">Papayaya & Crisps</a></li>
                            <li><a href="#">Oatmeal</a></li>
                            <li><a href="#">Fresh Bananas</a></li>
                        </ul>
                    </div>
                </div> {% endcomment %}
                <div class="col-lg-12">
                    <div class="hero__search">
                        <div class="hero__search__form">
                            <form action="#">
                                <div class="hero__search__categories">
                                    All Categories
                                    <span class="arrow_carrot-down"></span>
                                </div>
                                <input type="text" placeholder="What do yo u need?">
                                <button type="submit" class="site-btn">SEARCH</button>
                            </form>
                        </div>
                        <div class="hero__search__phone">
                            <div class="hero__search__phone__icon">
                                <i class="fa fa-phone"></i>
                            </div>
                            <div class="hero__search__phone__text">
                                <h5>+8801760114620</h5>
                                <span>support 24/7 time</span>
                            </div>
                        </div>
                    </div>
                    {% block banner %}
                        

                    {% endblock banner %}
                </div>
            </div>
        </div>
    </section>
    
    {% block body %}
    
    {% endblock body %}



   <!-- Footer Section Begin -->
   <footer class="footer spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="footer__about">
                    <div class="footer__about__logo">
                        <a href="./index.html"><img src="{% static 'assets/img/logo.png' %}" alt=""></a>
                    </div>
                    <ul>
                        <li>Address: H 46 Road -10
                            Dhaka 1230
                            Bangladesh</li>
                        <li>Phone: +01760114620</li>
                        <li>Email: sasomona8@gmail.com</li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
                <div class="footer__widget">
                    <h6>Useful Links</h6>
                    <ul>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">About Our Shop</a></li>
                        <li><a href="#">Secure Shopping</a></li>
                        <li><a href="#">Delivery infomation</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Our Sitemap</a></li>
                    </ul>
                    <ul>
                        <li><a href="#">Who We Are</a></li>
                        <li><a href="#">Our Services</a></li>
                        <li><a href="#">Projects</a></li>
                        <li><a href="{% url 'home:contact' %}">Contact</a></li>
                        <li><a href="#">Innovation</a></li>
                        <li><a href="#">Testimonials</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-12">
                <div class="footer__widget">
                    <h6>Join Our Newsletter Now</h6>
                    <p>Get E-mail updates about our latest shop and special offers.</p>
                    <form action="#">
                        <input type="text" placeholder="Enter your mail">
                        <button type="submit" class="site-btn">Subscribe</button>
                    </form>
                    <div class="footer__widget__social">
                        <a href="https://www.facebook.com/somona.akter.16144" target="_blank"><i class="fa fa-facebook"></i></a>
                        <a href="https://www.facebook.com/somona.akter.16144" target="_blank"><i class="fa fa-instagram"></i></a>
                        <a href="https://www.facebook.com/somona.akter.16144" target="_blank"><i class="fa fa-twitter"></i></a>
                        <a href="https://www.facebook.com/somona.akter.16144" target="_blank"><i class="fa fa-pinterest"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="footer__copyright">
                    <div class="footer__copyright__text"><p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://iubat.edu" target="_blank">Sumona</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p></div>
                    <div class="footer__copyright__payment"><img src="{% static 'assets/img/payment-item.png' %}" alt=""></div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section End -->

<!-- Js Plugins -->
<script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'assets/js/jquery-ui.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.slicknav.js' %}"></script>
<script src="{% static 'assets/js/mixitup.min.js' %}"></script>
<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>



</body>

</html>