accounts/urls.py
from django.urls import path


# accounts views
from accounts.views import SignupView
from accounts.views import UserLogout
from accounts.views import UserLoginView

app_name = 'accounts'


urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', UserLogout.as_view(), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.views import serve
from django.conf import settings


# Apps Urls
from accounts import urls as accounts_urls
from authority import urls as authority_urls
from customer import urls as customer_urls
from home import urls as home_urls
from payment import urls as payment_urls
from report import urls as report_urls
from shipping import urls as shipping_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(accounts_urls)),
    path('', include(authority_urls)),
    path('', include(customer_urls)),
    path('', include(home_urls)),
    path('', include(payment_urls)),
    path('', include(report_urls)),
    path('', include(shipping_urls)),

]

# for serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, view=serve)

home/urls.py
from django.urls import path

# Views
from home.views import home_main
from home.views import customer_message

app_name = 'home'

urlpatterns = [

    path('', home_main.IndexView.as_view(),name="index"),
    path('home/', home_main.IndexView.as_view(),name="home"),
    path('contact/', home_main.ContactView.as_view(),name="contact"),
    
]

urlpatterns += [
    path('customer-message/', customer_message.CustomerMessageView.as_view(), name='customer_message'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy


# uploaded file path
from accounts.utils import user_directory_path


# Create your models here.
class MyUserManager(BaseUserManager):

    """A custom manager to deal with emails and custom identifiers"""

    def _create_user(self, email, password, **extra_fields):
        """A custom manager to deal with emails and custom identifiers"""
        if not email:
            raise ValueError('Users must have an email address')
        
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_customer(self, email, password, **extra_fields):
        user = self._create_user(email, password, **extra_fields)
        user.is_customer = True
        user.save(using=self._db)
        return user
    
    def create_deleveryman(self, email, password, **extra_fields):
        user = self._create_user(email, password, **extra_fields)
        user.is_deleveryman = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError("superuser must have is_staff=True")
        
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('superuser must have is_superuser=True')
        
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, null=False)
    is_customer = models.BooleanField(default=False)
    is_deleveryman=models.BooleanField(default=False)
    is_staff = models.BooleanField(
        gettext_lazy('staff_status'), default=False,
        help_text=gettext_lazy('designates whether the user can login to this site'),
    )

    is_active = models.BooleanField(
        gettext_lazy('active'), default=True,
        help_text=gettext_lazy('designates whether the user can loin to this site'),
    )

    USERNAME_FIELD = 'email'

    objects = MyUserManager()

    def __str__(self):
        return self.email
    
    def get_full_name(self):
        return self.email
    
    def get_short_name(self):
        return self.email


# profile models gender choices
GENDER_OPT = (
    ('male', 'Male'),
    ('female', 'Female'),
    ('other', 'Other')
)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    first_name = models.CharField(max_length=264, blank=True)
    last_name = models.CharField(max_length=15, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER_OPT)
    photo = models.ImageField(upload_to=user_directory_path, null=True, default='default/user.jpg')
    date_of_join = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.first_name+"'s profile"


class Address(models.Model):
    address_of = models.OneToOneField(User, on_delete=models.CASCADE, related_name='address')
    phone_no = models.CharField(max_length=15)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    division = models.CharField(max_length=50)
    district = models.CharField(max_length=50)
    post_code = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.address_of}'s Present Address"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

# models
from accounts.models import User
from accounts.models import Profile
from accounts.models import Address

# Widgets
from accounts.widgets import CustomPictureImageFieldWidget


# forms
class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class ProfileForm(forms.ModelForm):
    photo = forms.ImageField(widget=CustomPictureImageFieldWidget)

    class Meta:
        model = Profile
        exclude = ('user',)


class AddressForm(forms.ModelForm):

    class Meta:
        model = Address
        exclude = ('address_of',)

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import HttpResponse
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect


# Permission and Authentication
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout

from django.contrib.auth.mixins import LoginRequiredMixin


# class based view builtin class
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.views.generic import CreateView

# Models
from accounts.models import User

# forms
from django.contrib.auth.forms import AuthenticationForm
from accounts.forms import SignUpForm


# Create your views here.
class SignupView(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'accounts/signup.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Customer Signup"
        return context
    
    def form_valid(self, form):
        try:
            form_obj=form.save()
            form_obj.is_customer = True
            form_obj.save()
            messages.success(self.request, "Welcome to Sizzling Station")
            return super().form_valid(form)
        
        except Exception as e:
            print(e)
            return self.form_invalid(form)
        
    def form_invalid(self, form):
        email = form.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            messages.error(self.request, "Thsi email already exist try another or login")
        return super().form_invalid(form)
        
    


class UserLoginView(LoginView):
    form_class = AuthenticationForm
    success_url = reverse_lazy('home:home')
    template_name = 'accounts/login.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Login Page" 
        return context
    
    
    def form_valid(self, form):
        username = self.request.POST['username']
        password = self.request.POST['password']

        try:
            request_user = User.objects.get(email=username)
            user = authenticate(self.request, username=username, password=password)

            if user is not None and request_user.is_superuser is True and request_user.is_staff is True:
                login(self.request, user)
                return HttpResponseRedirect(reverse('authority:authority'))
            
            elif user is not None and request_user.is_customer is True:
                login(self.request, user)
                self.success_url = self.request.GET.get('next', self.success_url)
                return HttpResponseRedirect(self.get_success_url())

            elif user is not None and request_user.is_deleveryman is True:
                login(self.request, user)
                return HttpResponse("Delevery Man login page will implement soon")

            
            else:
                if User.objects.filter(email=username).exists() and request_user.is_active is False:
                    messages.warning(self.request, f"{username} this email don't have login permission")
                
                return HttpResponseRedirect(reverse('accounts:login'))

        except Exception as e:
            print(e)
            return self.form_invalid(form)
    
    def form_invalid(self, form):
        messages.error(self.request, "Invalid User email password")
        return super().form_invalid(form)
    

class UserLogout(LoginRequiredMixin, LogoutView):
    def get(self, request, *args, **kwargs):
        user = self.request.user
        logout(request)
        if user.is_customer:
           return redirect(reverse('home:home'))
        return redirect(reverse('accounts:login'))

accounts/templates/accounts/login.html
{% extends 'accounts_base/accounts_base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %} {{title}} {% endblock title %}

{% block body %}
 <!-- Sign In Start -->
 <div class="container-fluid">
    <div class="row h-100 align-items-center justify-content-center" style="min-height: 100vh;">
        <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4">
            <div class="bg-dark rounded p-4 p-sm-5 my-4 mx-3">
                <div class="d-flex align-items-center justify-content-between mb-3">
                    <a href="{% url 'home:index' %}" class="">
                        <h3 class="text-white"><i class="fa-solid fa-burger text-primary me-2"></i>SIZZ<span class="text-primary">LING</span></h3>
                    </a>
                    <h3 class="text-primary">Sign In</h3>
                </div>
                <form action="" method="POST">{% csrf_token %}
                    <div class="form-floating mb-3">
                        {{form.username | add_class:"form-control"}}
                        <label for="floatingInput">Email address</label>
                    </div>
                    <div class="form-floating mb-4">
                        {{form.password | add_class:"form-control"}}
                        <label for="floatingPassword">Password</label>
                    </div>
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">Check me out</label>
                        </div>
                        <a href="" class="text-white">Forgot Password</a>
                    </div>
                    <button type="submit" class="btn btn-primary py-3 w-100 mb-4">Sign In</button>
                    <p class="text-center mb-0 text-white"" >Don't have an Account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>

                </form>
            </div>
        </div>
    </div>
</div>
<!-- Sign In End -->

{% endblock body %}

accounts/templates/accounts/signup.html
{% extends 'accounts_base/accounts_base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %} {{title}} {% endblock title %}

{% block body %}
<!-- Sign Up Start -->
<div class="container-fluid">
    <div class="row h-100 align-items-center justify-content-center" style="min-height: 100vh;">
        <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4">
            <div class="bg-dark rounded p-4 p-sm-5 my-4 mx-3">
                <div class="d-flex align-items-center justify-content-between mb-3">
                    <a href="{% url 'home:index' %}" class="">
                        <h3 class="text-white"><i class="fa-solid fa-burger text-primary me-2"></i></i>SIZZ<span class="text-primary">LING</span></h3>
                    </a>
                    <h3 class="text-primary">Sign Up</h3>
                </div>
                <form action="" method="POST"> {% csrf_token %}
                    <div class="form-floating mb-3">
                        {{form.email | add_class:"form-control"}}
                        <label for="floatingInput">Email address</label>
                    </div>
                    <div class="form-floating mb-4">
                        {{form.password1 | add_class:"form-control" }}
                        <label for="floatingPassword">Password</label>
                    </div>
                    <div class="form-floating mb-4">
                        {{form.password2 | add_class:"form-control" }}
                        <label for="floatingPassword">Confirm Password</label>
                    </div>
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">Check me out</label>
                        </div>
                        <a href="" class="text-white">Forgot Password</a>
                    </div>
                    <button type="submit" class="btn btn-primary py-3 w-100 mb-4">Sign Up</button>
                    <p class="text-center mb-0 text-white">Already have an Account? <a href="{% url 'accounts:login' %}">Sign In</a></p>
                </form>
                
            </div>
        </div>
    </div>
</div>
<!-- Sign Up End -->

{% endblock body %}